"""
Django settings for betatrax project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import importlib.util
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def _load_dotenv(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        key, value = raw.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_dotenv(BASE_DIR / ".env")


def _env_flag(name: str, default: str = "False") -> bool:
    return os.getenv(name, default).lower() in {"1", "true", "yes", "on"}


HAS_DJANGO_TENANTS = importlib.util.find_spec("django_tenants") is not None
HAS_DRF_SPECTACULAR = importlib.util.find_spec("drf_spectacular") is not None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#gy1nwck5!1e@@qcey(j36qe)s5f365s!$fn3hw##3k$5wd2lh'

# SECURITY WARNING: don't run with debug turned on in production!
# Default True for local development convenience; set DJANGO_DEBUG=False in production.
DEBUG = _env_flag("DJANGO_DEBUG", "True")

def _split_csv_env(name: str) -> list[str]:
    raw = os.getenv(name, "")
    return [item.strip() for item in raw.split(",") if item.strip()]


ALLOWED_HOSTS = _split_csv_env("DJANGO_ALLOWED_HOSTS")
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

PUBLIC_SCHEMA_DOMAINS = _split_csv_env("PUBLIC_SCHEMA_DOMAINS")
for public_domain in PUBLIC_SCHEMA_DOMAINS:
    if public_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(public_domain)

CSRF_TRUSTED_ORIGINS = _split_csv_env("DJANGO_CSRF_TRUSTED_ORIGINS")

# Always trust local development origins to avoid CSRF false positives
# when switching between localhost/127.0.0.1 and different ports.
for origin in [
    "http://localhost",
    "http://127.0.0.1",
    "https://localhost",
    "https://127.0.0.1",
]:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Respect X-Forwarded-* headers when running behind a reverse proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True


# Application definition

USE_DJANGO_TENANTS = _env_flag("ENABLE_DJANGO_TENANTS", "False") and HAS_DJANGO_TENANTS

BASE_INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tenancy',
    'defects',
    'frontend',
]

if HAS_DRF_SPECTACULAR:
    BASE_INSTALLED_APPS.append('drf_spectacular')

TENANT_MODEL = 'tenancy.Tenant'
TENANT_DOMAIN_MODEL = 'tenancy.Domain'

if USE_DJANGO_TENANTS:
    SHARED_APPS = [
        'django_tenants',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'rest_framework',
        'tenancy',
    ]
    if HAS_DRF_SPECTACULAR:
        SHARED_APPS.append('drf_spectacular')

    TENANT_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'rest_framework',
        'defects',
        'frontend',
    ]
    if HAS_DRF_SPECTACULAR:
        TENANT_APPS.append('drf_spectacular')

    INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]
else:
    INSTALLED_APPS = BASE_INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if USE_DJANGO_TENANTS:
    MIDDLEWARE.insert(0, 'tenancy.middleware.PublicDomainTenantMiddleware')
    PUBLIC_SCHEMA_URLCONF = 'betatrax.public_urls'
    SHOW_PUBLIC_IF_NO_TENANT_FOUND = _env_flag("SHOW_PUBLIC_IF_NO_TENANT_FOUND", "True")

ROOT_URLCONF = 'betatrax.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'betatrax.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_ENGINE = os.getenv("DATABASE_ENGINE", "sqlite").strip().lower()
if DATABASE_ENGINE == "postgresql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'betatrax'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(Path(os.getenv("SQLITE_PATH", str(BASE_DIR / 'db.sqlite3')))),
        }
    }

if USE_DJANGO_TENANTS:
    if DATABASE_ENGINE != "postgresql":
        raise ImproperlyConfigured("ENABLE_DJANGO_TENANTS=True requires DATABASE_ENGINE=postgresql.")
    DATABASES['default']['ENGINE'] = 'django_tenants.postgresql_backend'
    DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
}

if HAS_DRF_SPECTACULAR:
    REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "drf_spectacular.openapi.AutoSchema"
    SPECTACULAR_SETTINGS = {
        "TITLE": "BetaTrax API",
        "DESCRIPTION": "BetaTrax defect management API documentation",
        "VERSION": "v3",
    }


# Email
EMAIL_ENABLED = os.getenv("EMAIL_ENABLED", "False").lower() in {"1", "true", "yes", "on"}
if EMAIL_ENABLED:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {"1", "true", "yes", "on"}
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in {"1", "true", "yes", "on"}
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    default_sender = f"BetaTrax <{EMAIL_HOST_USER}>" if EMAIL_HOST_USER else "BetaTrax <noreply@betatrax.local>"
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", default_sender)
    SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
else:
    # For Sprint 1 demos/testing, print outgoing emails to server console.
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
