# Generated by Django 5.2.12 on 2026-04-26 12:50

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


def copy_existing_defects_tenant_registry(apps, schema_editor):
    existing_tables = schema_editor.connection.introspection.table_names()
    if "defects_tenant" not in existing_tables:
        return

    Tenant = apps.get_model("tenancy", "Tenant")
    Domain = apps.get_model("tenancy", "Domain")
    quote_name = schema_editor.connection.ops.quote_name

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, schema_name, domain, name, is_active, created_at FROM %s"
            % quote_name("defects_tenant")
        )
        tenant_rows = [dict(zip([column[0] for column in cursor.description], row)) for row in cursor.fetchall()]

    old_to_new_ids = {}
    for row in tenant_rows:
        tenant, _ = Tenant.objects.update_or_create(
            schema_name=row["schema_name"],
            defaults={
                "domain": row["domain"],
                "name": row["name"],
                "is_active": row["is_active"],
                "created_at": row["created_at"],
            },
        )
        old_to_new_ids[row["id"]] = tenant.pk

    if "defects_domain" in existing_tables:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT id, domain, is_primary, tenant_id FROM %s"
                % quote_name("defects_domain")
            )
            domain_rows = [dict(zip([column[0] for column in cursor.description], row)) for row in cursor.fetchall()]

        for row in domain_rows:
            tenant_id = old_to_new_ids.get(row["tenant_id"])
            if tenant_id is None:
                continue
            Domain.objects.update_or_create(
                domain=row["domain"],
                defaults={"tenant_id": tenant_id, "is_primary": row["is_primary"]},
            )
        return

    for tenant in Tenant.objects.all():
        Domain.objects.get_or_create(
            domain=tenant.domain,
            defaults={"tenant": tenant, "is_primary": True},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['schema_name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.RunPython(copy_existing_defects_tenant_registry, migrations.RunPython.noop),
    ]
