# Generated by Django 6.0.2 on 2026-03-24 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('owner_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('report_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('tester_id', models.CharField(max_length=64)),
                ('tester_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('Fixed', 'Fixed'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate'), ('Cannot Reproduce', 'Cannot Reproduce'), ('Reopened', 'Reopened')], default='New', max_length=32)),
                ('severity', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=16)),
                ('priority', models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=8)),
                ('backlog_ref', models.CharField(blank=True, max_length=64)),
                ('assignee_id', models.CharField(blank=True, max_length=64)),
                ('fix_note', models.TextField(blank=True)),
                ('retest_note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='defects.defectreport')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='defects.product')),
            ],
        ),
        migrations.CreateModel(
            name='DefectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defects.defectreport')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DefectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('Fixed', 'Fixed'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate'), ('Cannot Reproduce', 'Cannot Reproduce'), ('Reopened', 'Reopened')], max_length=32)),
                ('to_status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('Fixed', 'Fixed'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate'), ('Cannot Reproduce', 'Cannot Reproduce'), ('Reopened', 'Reopened')], max_length=32)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='defects.defectreport')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_id', models.CharField(max_length=64, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='defects.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'developer_id'), name='uniq_product_developer')],
            },
        ),
    ]
