# Generated by Django 5.2.12 on 2026-04-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_alter_tenant_schema_name_domain'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
